# Generated by Django 4.2.7 on 2026-02-04 18:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('cedula', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='La cédula solo puede contener números y guiones', regex='^[0-9\\-]+$')], verbose_name='Cédula')),
                ('telefono', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='El teléfono solo puede contener números y símbolos telefónicos', regex='^[0-9\\-\\+\\(\\)\\s]+$')], verbose_name='Teléfono')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('notas_medicas', models.TextField(blank=True, verbose_name='Notas médicas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='HistorialClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('procedimiento', 'Procedimiento'), ('tratamiento', 'Tratamiento'), ('observacion', 'Observación')], max_length=20, verbose_name='Tipo de registro')),
                ('fecha', models.DateField(verbose_name='Fecha del registro')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('notas', models.TextField(blank=True, verbose_name='Notas adicionales')),
                ('duracion', models.PositiveIntegerField(blank=True, help_text='Duración en minutos (solo para procedimientos)', null=True, verbose_name='Duración (minutos)')),
                ('costo', models.DecimalField(blank=True, decimal_places=2, help_text='Costo del procedimiento (solo para procedimientos)', max_digits=10, null=True, verbose_name='Costo')),
                ('duracion_estimada', models.PositiveIntegerField(blank=True, help_text='Duración estimada en días (solo para tratamientos)', null=True, verbose_name='Duración estimada (días)')),
                ('frecuencia', models.CharField(blank=True, help_text='Frecuencia del tratamiento (solo para tratamientos)', max_length=100, verbose_name='Frecuencia')),
                ('gravedad', models.CharField(blank=True, choices=[('leve', 'Leve'), ('moderada', 'Moderada'), ('grave', 'Grave')], help_text='Gravedad de la observación (solo para observaciones)', max_length=20, verbose_name='Gravedad')),
                ('requiere_seguimiento', models.BooleanField(default=False, help_text='Requiere seguimiento (solo para observaciones)', verbose_name='Requiere seguimiento')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Registro del historial clínico',
                'verbose_name_plural': 'Registros del historial clínico',
                'ordering': ['-fecha', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y hora')),
                ('motivo', models.CharField(max_length=200, verbose_name='Motivo de consulta')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('atendida', 'Atendida'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('notas', models.TextField(blank=True, verbose_name='Notas adicionales')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['fecha_hora'],
            },
        ),
    ]
